version: '3.8'

services:
  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "15MB"

  app1:
    build: .
    hostname: app1
    networks:
      - backend
      - payment-processor
    volumes:
      - ./data:/app/data
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "167MB"

  app2:
    build: .
    hostname: app2
    networks:
      - backend
      - payment-processor
    volumes:
      - ./data:/app/data
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.625"
          memory: "167MB"

networks:
  backend:
    driver: bridge

  payment-processor:
    external: true
